name: Feature request
description: Propose a new agent-aware or documentation feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to suggest a new feature (e.g. new MCP tool, plugin option, or agent-facing behavior). Describe the problem and your proposed solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What problem does this solve, or what use case does it enable?
      placeholder: |
        e.g. Agents need a way to know which pages were updated recently so they can prioritize reading. Currently there is no "last modified" signal in the sitemap or payload.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? (API, config, new tool, etc.)
      placeholder: |
        e.g. Add an optional `lastModified` field to LLM_Meta and emit it in llm-sitemap.json and agent payload. MCP list_documentation_pages could include it.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Where would this fit?
      options:
        - "Vite plugin / build"
        - "MCP server / tools"
        - "Search index / BM25"
        - ".vllm format / LLM_Meta"
        - "Sitemap / llm-sitemap.json"
        - "Agent detection / routing"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought about (optional).
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Mockups, examples, or references.
